### ISSUE TITLE
RTL in navigation

### ISSUE THREAD

**Issue by a3ammar** [rastersize/BlogTheme#7]
I'm trying to modify your theme into a RTL layout, everything works except the navigation. I tried to use direction property, dir tag but nothing works. Can you help me find a way?

Here's my site http://fast-peak-5148.herokuapp.com/

**Comment by rastersize** [comment]
Hmm, not sure how to fix it properly (as I’m not really a web-guy). The problem seems to be that the `a`-elements in the list items are set to the width of the text. The text is then set to go from right to left but the `a`-element is laid out from the left. It look correct if I changed the width of the `a`-elements to `137 px` (as that is the final width of the parent `li` items). This width seemed to work in all sizes of the browser window.

Unfortunately I don’t have a proper solution, only the hack mentioned above which at least works.

**Comment by a3ammar** [comment]
Thanks a lot, that seems to work.
